### ISSUE TITLE
setup.sh Carthage build fails due to swift 3 vs 4 incompatibilities, cocoapods instal aborts with a permissions violation

### ISSUE THREAD

**Issue by dang500** [mapbox/mapbox-arkit-ios#13]
Relevant files are attached. Trying to build  MapboxDirections by hand gives error message indicating that it is unhappy with the Polyline swift language level being less than 4. Not sure why there is a permissions fail with the cocoapods; 

relevant logs are attached as a zip archive:

[Install logs .zip](https://github.com/mapbox/mapbox-arkit-ios/files/1257906/Install.logs.zip)

**Comment by boundsj** [comment]
From your Carthage log:

> SDKROOT = iphoneos10.3

⬆️ it appears you are not using Xcode 9 Beta 5 or higher (iOS 11), at least not from the command line. You will probably need to use [xcode-select](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/xcode-select.1.html) to point to the beta Xcode once you have it installed before you attempt to build things from the command line like Carthage does.

I'm not sure about the CocoaPods issue. Is this from an attempt to use it in an application that you are building using an Xcode 9 Beta (not the setup.sh flow)? Can you share your podfile or a sample project that reproduces the issue?

**Comment by dang500** [comment]
xcode-select solved the carthage build issue; the demo app now builds and
runs - thanks!.

The cocoapods issue remains; I have included a zip of the project, which
includes the podfile that won't install. The project was created from an AR
app template, I then used the Cocoapods desktop app to create a default
podfile and workspace. I then copied and pasted the two podspecs (from the
instructions on github) into the podfile, and ran install (verbose). This
still produces the access violation message from the previous log.

Thanks,

Dan

**Comment by boundsj** [comment]
@dang500 it looks like your attempt to attach a zip did not work. Maybe because you replied via email? Can you please attach the zip file using the GitHub issues interface for this issue? Thanks!

**Comment by dang500** [comment]
Here it is: [MapboxTest.zip](https://github.com/mapbox/mapbox-arkit-ios/files/1258518/MapboxTest.zip)

**Comment by boundsj** [comment]
Thanks @dang500. It looks like I made a mistake in the readme. Can you please try using `https` in the Podfile instead of `ssh`? So, something like this:

```
  # The MapboxARKit pod
  pod 'MapboxARKit', :git => 'https://github.com/mapbox/mapbox-arkit-ios.git'

  # The Turf-swift dependency must be installed manually in the client app until the Turf pod is published on CocoaPods
  pod 'Turf-swift', :git => 'https://github.com/mapbox/turf-swift.git'
```

**Comment by boundsj** [comment]
https://github.com/mapbox/mapbox-arkit-ios/commit/9340a2b8839c6a486c1e4c70ebfa6ad1483701ce should address this confusion.
