### ISSUE TITLE
cat: mapbox_access_token: No such file or directory

### ISSUE THREAD

**Issue by geopast** [mapbox/mapbox-arkit-ios#14]
I'm pretty new at xcode and i've managed to install all the dependancies ok but stuck on this:

cat: mapbox_access_token: No such file or directory
error: Missing Mapbox access token
error: Get an access token from <https://www.mapbox.com/studio/account/tokens/>, then create a new file at mapbox_access_token that contains the access token.

I edited the empty file and replaced all the text with the key. However i cannot see why it does not see the file. I have the same problem with the SafetyTour example (https://blog.mapbox.com/model-the-real-world-with-the-new-arkit-library-d822e316f27d). The file is there but the script does not see it?

Thanks!

**Comment by drougojrom** [comment]
Hi, @geopast !
You need to create file mapbox_access_token on the root folder of the project, like this: 
<img width="260" alt="screen shot 2017-09-18 at 3 30 34 pm" src="https://user-images.githubusercontent.com/16073082/30544320-5f5ce7e6-9c86-11e7-8df9-f543f5ad5219.png">

**Comment by geopast** [comment]
OK for some reason it worked this time :) Managed to build this app on my 6S. Thank you. I am still struggling with SafetyTour. The error in Xcode is: No such module 'MapboxARKit'. I'm following the Readme (attached). 
Thanks!
[README.md.txt](https://github.com/mapbox/mapbox-arkit-ios/files/1312598/README.md.txt)

**Comment by geopast** [comment]
Thanks  - all solved!
