### ISSUE TITLE
Type 'Turf' has no member 'distance'

### ISSUE THREAD

**Issue by sriteja25** [mapbox/mapbox-arkit-ios#17]
I am trying to run the demo project and i get this error in the line

let distance = Turf.distance(along: polyline)

**Comment by phr85** [comment]
I have same problem here 🤔

**Comment by boundsj** [comment]
https://github.com/mapbox/turf-swift/pull/9 refactored Turf-swift's polyline API and removed the `distance(along:)` method on Turf proper. I just merged https://github.com/mapbox/mapbox-arkit-ios/pull/18 that updates this library's implementation to use the new Swift-turf APIs which should address this issue.

**Comment by sriteja25** [comment]
Thank you for the update 👍
