### ISSUE TITLE
Incorrect Turf dependency

### ISSUE THREAD

**Issue by newkirkjosh** [mapbox/mapbox-arkit-ios#19]
According to the [Turf](https://github.com/mapbox/turf-swift/blob/master/Turf.podspec) docs, the name is only `Turf` not `Turf-swift` making it impossible to use Cocoapods to integrate these projects.

My suggestion is to update the `mapbox-arkit-ios` dependency!

**Comment by boundsj** [comment]
Fixed in https://github.com/mapbox/mapbox-arkit-ios/pull/20. Turf-swift had a name change and was published to CocoaPods a few days ago in https://github.com/mapbox/turf-swift/commit/dccd622eeff5d274b65eef9ecd7b1b070fe2509d.
