### ISSUE TITLE
Update README language about beta version requirements

### ISSUE THREAD

**Issue by wangela** [mapbox/mapbox-arkit-ios#24]
> **Requirements:**
> * Xcode 9 Beta 5 or higher
> * An iDevice with an A9 (or greater) processor running iOS 11 Beta 5 or higher

Now that Xcode 9 and iOS 11 have been released, we just need those, right? Originally when I was evaluating whether to use this vs other libraries I was thrown off by the beta requirements and discounted it because it seemed incompatible with my timelines.

**Comment by boundsj** [comment]
This repo was created before Xcode 9 and iOS 11 were released. I updated the readme in https://github.com/mapbox/mapbox-arkit-ios/commit/a73ff0cd84e43b501530740898fd3a7cf5400e5f. Please note the warning at the top of the readme:

```

**Comment by boundsj** [comment]
Also, thanks for the report!
